# Generated by Django 4.1.6 on 2023-02-11 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TurkmenTelekechi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addresses', models.CharField(max_length=200, null=True)),
                ('telekechi_phone_numbers', models.CharField(max_length=20)),
                ('logos', models.ImageField(blank=True, upload_to='logos')),
                ('about_us', models.TextField(blank=True)),
                ('slug', models.SlugField(default='')),
            ],
        ),
    ]
