# Generated by Django 4.1.6 on 2023-02-18 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='credit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='delivery',
            field=models.BooleanField(default=False),
        ),
    ]
