# Generated by Django 4.1.7 on 2023-02-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_product_image2_product_product_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image4',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image5',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
    ]
