# Generated by Django 4.0.5 on 2023-03-06 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_userclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_adder',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='added_products', to='store.userclient'),
            preserve_default=False,
        ),
    ]
