# Generated by Django 4.0.5 on 2023-03-17 12:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_forgotpassword_turkmentelekechi_emails_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forgotpassword',
            name='posted_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
