# Generated by Django 4.0.5 on 2023-03-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_forgotpassword_posted_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': '4. Categories'},
        ),
        migrations.AlterModelOptions(
            name='forgotpassword',
            options={'verbose_name_plural': '3. Forgot passwords'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': '5. Products'},
        ),
        migrations.AlterModelOptions(
            name='turkmentelekechi',
            options={'verbose_name_plural': '1. Main site informations'},
        ),
        migrations.AlterModelOptions(
            name='userclient',
            options={'verbose_name_plural': '2. Clients'},
        ),
        migrations.AlterField(
            model_name='userclient',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
