# Generated by Django 4.0.5 on 2023-03-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_category_options_alter_forgotpassword_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclient',
            name='password_encrypted',
            field=models.BooleanField(default=False),
        ),
    ]
